name: Create release

# Triggered when a tag is pushed whose name starts with a "v" (intended for
# version tags)
on:
  push:
    tags:
      - v*

jobs:
  # Create a release with a downloadable zip file of the addons.
  # The release notes are pulled from the relevant version's section in the
  # changelog.
  create_release:
    name:    Create release
    runs-on: ubuntu-latest
    steps:
      - name: Get version name from tag
        id:   tag_name
        run:  echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Copy license file to addon folders
        run:  |
          cp LICENSE.md addons/Rereflect/LICENSE.md
      - name: Create zip file
        uses: papeloto/action-zip@v1
        with:
          files:     addons/
          dest:      Rereflect.zip
          recursive: true
      - name: Get relevant changelog entry
        id:   changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.version }}
          path:    ./CHANGELOG.md
      - name: Remove line breaks within changelog points
        id:   format_changelog
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value:       ${{ steps.changelog.outputs.changes }}
          regex:       "([^\n])(?:\n)([^-\n])"
          flags:       g
          replacement: "$1 $2"
      - name: Create release
        id:   create_release
        uses: actions/create-release@v1
        with:
          tag_name:     ${{ github.ref }}
          release_name: Version ${{ steps.changelog.outputs.version }}
          body:         ${{ steps.format_changelog.outputs.value }}
          draft:        false
          prerelease:   true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload zip to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url:         ${{ steps.create_release.outputs.upload_url }}
          asset_path:         Rereflect.zip
          asset_name:         Rereflect.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
